name: Build-All-Platforms

on:
  push:
    branches: [ "releases" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Directory setup
        run: mkdir ${{ matrix.os }}-build

      - name: Configuration cmake for release build
        run: cmake -B ${{github.workspace}}/${{ matrix.os }}-build -DCMAKE_BUILD_TYPE=Release

      - name: Release build
        run: cmake --build ${{github.workspace}}/${{ matrix.os }}-build --config Release

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} build
          path: ./${{ matrix.os }}-build/*