name: _Makefile CI

on:
  push:
    branches: [ "releases" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Directory setup
      run: mkdir ubuntu-build

    - name: Configuration cmake for release build
      run: cmake -B ${{github.workspace}}/ubuntu-build -DCMAKE_BUILD_TYPE=Release

    - name: Release build
      run: cmake --build ${{github.workspace}}/ubuntu-build --config Release

    - name: Upload built artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu_built_solver
        path: ./ubuntu-build/*

  build-windows:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Directory setup
      run: mkdir windows-build

    - name: Configuration cmake for release build
      run: cmake -B ${{github.workspace}}/windows-build -DCMAKE_BUILD_TYPE=Release

    - name: Release build
      run: cmake --build ${{github.workspace}}/windows-build --config Release

    - name: Upload built artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_built_solver
        path: ./windows-build/*