name: Build-All-Platforms

on:
  push:
    branches: [ "releases" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    env:
      CMAKE_BUILD_TYPE: 'Release'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          runVcpkgInstall: true

      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} build
          path: ${{ runner.os }}-build/mechanics*
