name: _Makefile CI

on:
  push:
    branches: [ "releases" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: 'Release'
      CONFIGURE_PRESET_NAME: 'ubuntu'
      BUILD_PRESET_NAME: 'ubuntu-build'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          runVcpkgInstall: true

      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: default
          buildPreset: default
          useVcpkgToolchainFile: true

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu_built_solver
          path: ubuntu-build/*

  build-windows:
  
    runs-on: windows-latest
    env:
      CMAKE_BUILD_TYPE: 'Release'
      CONFIGURE_PRESET_NAME: 'windows'
      BUILD_PRESET_NAME: 'windows-build'
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          runVcpkgInstall: true

      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: default
          buildPreset: default
          useVcpkgToolchainFile: true

      - name: Upload built artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_built_solver
          path: windows-build/*